# Use an official Node.js runtime as a parent image
FROM node:18

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy the package.json and package-lock.json files to the working directory
COPY package*.json ./

# Install any dependencies
RUN npm install

# Copy the rest of your application files to the working directory
COPY . .

# Build the NestJS application
RUN npm run build

# Expose the port that the app runs on
EXPOSE 3000

# Define the command to run your app
CMD ["npm", "run", "start:prod"]